CREATE TABLE public.persistent_logins (
  username CHARACTER VARYING(64) NOT NULL,
  series CHARACTER VARYING(64) PRIMARY KEY NOT NULL,
  token CHARACTER VARYING(64) NOT NULL,
  last_used TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now()
);
CREATE TABLE public."user" (
  name CHARACTER VARYING(255) PRIMARY KEY NOT NULL,
  active INTEGER,
  email CHARACTER VARYING(255),
  login_date TIMESTAMP WITHOUT TIME ZONE,
  password CHARACTER VARYING(255),
  phone CHARACTER VARYING(255),
  verification CHARACTER VARYING(255),
  description CHARACTER VARYING(255)
);
CREATE TABLE public.role_mapping (
  user_id CHARACTER VARYING(255) NOT NULL,
  role_uid BIGINT NOT NULL,
  FOREIGN KEY (user_id) REFERENCES "user" (name)
  MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION,
  FOREIGN KEY (role_uid) REFERENCES user_role (id)
  MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION
);
CREATE TABLE public.user_role (
  id BIGINT PRIMARY KEY NOT NULL,
  name CHARACTER VARYING(255)
);



CREATE TABLE public.cloth_fabric (
  id BIGINT PRIMARY KEY NOT NULL DEFAULT nextval('cloth_fabric_id_seq'::regclass),
  color CHARACTER VARYING(255),
  description CHARACTER VARYING(255),
  height CHARACTER VARYING(255),
  name CHARACTER VARYING(255),
  paint CHARACTER VARYING(255),
  photo CHARACTER VARYING(255),
  photo01 CHARACTER VARYING(255),
  photo02 CHARACTER VARYING(255),
  photo03 CHARACTER VARYING(255),
  photo04 CHARACTER VARYING(255),
  photo05 CHARACTER VARYING(255),
  price NUMERIC(19,2),
  quantity DOUBLE PRECISION,
  structure CHARACTER VARYING(255)
);
CREATE TABLE public.curtain (
  id BIGINT PRIMARY KEY NOT NULL DEFAULT nextval('curtain_id_seq'::regclass),
  color CHARACTER VARYING(255),
  description CHARACTER VARYING(255),
  height CHARACTER VARYING(255),
  name CHARACTER VARYING(255),
  paint CHARACTER VARYING(255),
  photo CHARACTER VARYING(255),
  photo01 CHARACTER VARYING(255),
  photo02 CHARACTER VARYING(255),
  photo03 CHARACTER VARYING(255),
  photo04 CHARACTER VARYING(255),
  photo05 CHARACTER VARYING(255),
  price NUMERIC(19,2),
  quantity DOUBLE PRECISION,
  structure CHARACTER VARYING(255)
);
CREATE TABLE public.order_curtain (
  id BIGINT PRIMARY KEY NOT NULL DEFAULT nextval('order_curtain_id_seq'::regclass),
  color CHARACTER VARYING(255),
  description CHARACTER VARYING(255),
  height CHARACTER VARYING(255),
  name CHARACTER VARYING(255),
  paint CHARACTER VARYING(255),
  photo CHARACTER VARYING(255),
  photo01 CHARACTER VARYING(255),
  photo02 CHARACTER VARYING(255),
  photo03 CHARACTER VARYING(255),
  photo04 CHARACTER VARYING(255),
  photo05 CHARACTER VARYING(255),
  price NUMERIC(19,2),
  quantity DOUBLE PRECISION,
  structure CHARACTER VARYING(255)
);
CREATE TABLE public.tulle (
  id BIGINT PRIMARY KEY NOT NULL DEFAULT nextval('tulle_id_seq'::regclass),
  color CHARACTER VARYING(255),
  description CHARACTER VARYING(255),
  height CHARACTER VARYING(255),
  name CHARACTER VARYING(255),
  paint CHARACTER VARYING(255),
  photo CHARACTER VARYING(255),
  photo01 CHARACTER VARYING(255),
  photo02 CHARACTER VARYING(255),
  photo03 CHARACTER VARYING(255),
  photo04 CHARACTER VARYING(255),
  photo05 CHARACTER VARYING(255),
  price NUMERIC(19,2),
  quantity DOUBLE PRECISION,
  structure CHARACTER VARYING(255)
);
CREATE TABLE public.upholstery_fabric (
  id BIGINT PRIMARY KEY NOT NULL DEFAULT nextval('upholstery_fabric_id_seq'::regclass),
  color CHARACTER VARYING(255),
  description CHARACTER VARYING(255),
  height CHARACTER VARYING(255),
  name CHARACTER VARYING(255),
  paint CHARACTER VARYING(255),
  photo CHARACTER VARYING(255),
  photo01 CHARACTER VARYING(255),
  photo02 CHARACTER VARYING(255),
  photo03 CHARACTER VARYING(255),
  photo04 CHARACTER VARYING(255),
  photo05 CHARACTER VARYING(255),
  price NUMERIC(19,2),
  quantity DOUBLE PRECISION,
  structure CHARACTER VARYING(255)
);